### ISSUE TITLE
Ficheros ocultos del sistema operativo en Github

### ISSUE THREAD

**Issue by cr0hn** [cybercamp18isecurity/iSecurityAssistant#1]
<img width="650" alt="cybercamp18isecurity_isecurityassistant" src="https://user-images.githubusercontent.com/4076390/49303387-de4d1e80-f4c9-11e8-8815-949bdc47f1e2.png">

**Comment by lucferbux** [comment]
Añadido en el gitignore todos los archivos ocultos del sistema
